### PR TITLE
Update dependency to react v15

### PR DESCRIPTION
**Pull request by aight8**

### CODE REVIEW

**Comment by acamari** [comment]
Hi, did you have any comments on this?

**Comment by rg1220** [comment]
@jstejada Any update?

**Comment by milankorsos** [comment]
@jstejada Love your work! Can we help with anything to get this PR merged?

**Comment by jstejada** [comment]
hi all! thanks for the PR @aight8. Sorry for the delay in getting back to you!

**Comment by glennreyes** [comment]
@jstejada Thanks for that! 💪 Could you please bump this package to 0.3.1 on npm?

**Comment by jstejada** [comment]
yes! will publish a new version really soon, sorry for the delay! thanks!

**Comment by maximebonhomme** [comment]
@jstejada any news on that version bump? thanks!

**Pull request merged**
