### PR TITLE
Clean up timeouts on unmount

### PR DESCRIPTION
**Pull request by devdoomari**
This commit fixes invalid setState() when react-typist unmounts before finishing its animation.

### CODE REVIEW

**Comment by milan-hgdata** [comment]
@jstejada Do you have an ETA when this will get merged and included in a stable release? Thank you!

**Comment by milankorsos** [comment]
@jstejada Juan, do you have an ETA when this will be merged and included in a stable release? Thank you!

**Comment by jstejada** [comment]
Hi @devdoomari, thanks for submitting this pull request, I really appreciate it!
This is great! However, could you scope this PR to just the fix mentioned in the title? This PR includes several seemingly unrelated changes to the build config, and an ie polyfill, which I'm happy to take in a different PR if necessary. There is also no need to include built output in the commits, I can commit the built output when I bump the version.

Thanks a lot! Happy to merge this in when its updated!

cc @milankorsos

**Comment by devdoomari** [comment]
@jstejada you're right about this pull req. doing more than one thing.
I had to do so because I needed IE9+ support too for my company's website.
Anyway, I'll do separate pull requests for each of them a bit later, but anyone's welcome to do their own pull request based on mine.

cc @milankorsos

**Comment by jstejada** [comment]
okay, thanks anyway @devdoomari! Closing this in favor of #12

**Pull request closed without merging**
