### PR TITLE
Backspace and delay in development mode

### PR DESCRIPTION
**Pull request by yjimk**
Hi there!

Thanks for the library, it's been really handy!

I've been having a minor issue with it though in when running in Gatsby development mode, working perfect when doing a production build. 

I think similar issues have been reported before, but they were closed.
https://github.com/jstejada/react-typist/issues/45
https://github.com/jstejada/react-typist/issues/56

Not sure if the version published to NPM (2.0.4) is up to date with master either, looks like it's 3 commits behind.

### CODE REVIEW

**Comment by kvandake** [comment]
Any status on updating the library?

**Comment by ahansson89** [comment]
@jstejada Can you merge this in, please? Thanks!

**Comment by jstejada** [comment]
@yjimk thanks for the update, and apologies for the delay in getting to this. 

Quick question, what's the reason for making the additional changes to how we check the element type? Is the fix currently on master not sufficient

**Comment by yjimk** [comment]
Thanks, just reverted the change in package.json now

The extra check is due to (for reasons unknown to me) the property name for the value we need to check being different when NODE_ENV is 'development' instead of 'production'.

The rest of the checks are just guards so no unexpected values slip through and throw errors :D

**Comment by yjimk** [comment]
Hi there! Are you planning on merging this one in?

**Comment by jstejada** [comment]
Hey, thanks and sorry for the delay in getting to this. merging it in!

**Pull request merged**
